services:

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "${INFLUXDB_HTTP_PORT}:8086"
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - influxdb-data:/var/lib/influxdb

  telegraf:
    image: telegraf:1.29
    container_name: telegraf
    depends_on:
      - influxdb
    ports:
      - "${TELEGRAF_STATSD_PORT}:${TELEGRAF_STATSD_PORT}/udp"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    depends_on:
      - telegraf
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources

volumes:
  influxdb-data:
  grafana-data:
